{
 "title": "PlantMonitor",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Hourly data",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "moisture",
     "query": "SELECT 100 - ((last(\"sense\")  - 300) / 6) AS \"moist est last\" FROM \"moisture\" WHERE $timeFilter GROUP BY time(1h), \"addr\" fill(none)",
     "select": [
      [
       { "params": [ "sense" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "moisture sense" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "moisture",
     "query": "SELECT 100 - ((mean(\"sense\")  - 300) / 6) AS \"moist est mean\" FROM \"moisture\" WHERE $timeFilter GROUP BY time(1h), \"addr\" fill(none)",
     "select": [
      [
       { "params": [ "sense" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "moisture sense" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "moisture",
     "query": "SELECT last(\"sense\") AS \"moist raw last\" FROM \"moisture\" WHERE $timeFilter GROUP BY time(1h), \"addr\" fill(none)",
     "select": [
      [
       { "params": [ "sense" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "moisture",
     "query": "SELECT mean(\"sense\") AS \"moist raw mean\" FROM \"moisture\" WHERE $timeFilter GROUP BY time(1h), \"addr\" fill(none)",
     "select": [
      [
       { "params": [ "sense" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "select": [
      [
       { "params": [ "vbat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "bat v last" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "select": [
      [
       { "params": [ "vbat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bat v mean" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Estimated Moisture",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "%" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "moisture",
     "query": "SELECT 100.0 - ( mean(\"sense\") - 300.0) / 6.0 FROM \"moisture\" WHERE $timeFilter GROUP BY time(5m), \"addr\" fill(none)",
     "select": [
      [
       { "params": [ "sense" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "select": [
      [
       { "params": [ "vbat" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}